language: nix

sudo: true

git:
  depth: 1

env:
  global:
  matrix:
    - GHCVERSION=ghc802
    - GHCVERSION=ghc822
    - GHCVERSION=ghc842

matrix:
  allow_failures:
    # It fails here because svg-builder hasn't been ported
    - GHCVERSION=ghc842
  exclude:

script:
  - nix-build --argstr compiler $GHCVERSION

branches:
  only:
    - master
