name:       hours
version:    3.0.0
synopsis:   Tool to print out hours worked toward a goal
author:     John Wiegley
maintainer: johnw@newartisans.com
github:     jwiegley/hours
category:   System
license:    MIT

dependencies:
  - aeson
  - base                 >= 4 && < 5
  - bytestring
  - optparse-applicative >= 0.5.2.1
  - process
  - these                >= 0.7.4
  - text
  - time                 >= 1.4
  - time-recurrence      >= 0.9.1

library:
  source-dirs: src
  exposed-modules:
    - Hours.Budget
    - Hours.Calc
    - Hours.Input
    - Hours.Time
    - Hours.Variant

executables:
  process-hours:
    main: Main.hs
    dependencies:
      - hours

  bae-periods:
    source-dirs: bae
    main: Main.hs
    other-modules:
      - BAE
    dependencies:
      - hours

  timelog-periods:
    source-dirs: timelog
    main: Main.hs
    other-modules:
      - Timelog
    dependencies:
      - hours
